# Generated by Django 5.0.4 on 2024-08-25 12:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('form_address', models.CharField(max_length=100)),
                ('to_address', models.CharField(max_length=100)),
                ('form_date', models.DateField()),
                ('to_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=18)),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('travel_companion', models.CharField(choices=[('family', 'Family'), ('friends', 'Friends'), ('partner', 'Partner'), ('solo', 'Solo'), ('doesnt_matter', 'Doesn’t Matter')], max_length=50)),
                ('preferences', models.CharField(choices=[('adventure', 'Adventure: Activities like hiking, rafting, zip-lining, etc.'), ('cultural', 'Cultural: Museums, historical sites, cultural tours, local experiences.'), ('relaxation', 'Relaxation: Beach resorts, spas, leisurely activities.'), ('nature_wildlife', 'Nature & Wildlife: National parks, safaris, nature trails, bird watching.'), ('amusement_parks', 'Amusement Parks: Theme parks, water parks, fun fairs.'), ('religious_spiritual', 'Religious/Spiritual: Pilgrimages, visits to temples, churches, mosques, meditation retreats.'), ('trekking', 'Trekking: Mountain treks, hiking trails, nature walks.'), ('food_culinary', 'Food & Culinary: Food tours, cooking classes, street food experiences, wine tasting.'), ('shopping', 'Shopping: Markets, shopping malls, local crafts.'), ('nightlife', 'Nightlife: Bars, clubs, live music, entertainment.'), ('festivals_events', 'Festivals & Events: Local festivals, music concerts, cultural events.'), ('art_architecture', 'Art & Architecture: Art galleries, architectural landmarks, design tours.'), ('photography', 'Photography: Scenic spots, photogenic locations, guided photography tours.'), ('wellness_spa', 'Wellness & Spa: Yoga retreats, wellness centers, spa treatments.'), ('offbeat_experiences', 'Offbeat Experiences: Unique, unconventional, and less crowded places.'), ('family_friendly', 'Family-Friendly: Activities suitable for all ages, family tours.'), ('doesnt_matter', 'Does not matter: Open to any kind of experience.')], max_length=50)),
                ('special_requests', models.TextField()),
            ],
        ),
    ]
