# Generated by Django 5.0.4 on 2024-08-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Itinerary',
            new_name='Itinerary_Input',
        ),
    ]
