# Generated by Django 5.0.4 on 2024-08-25 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_itinerary_itinerary_input'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary_input',
            old_name='form_address',
            new_name='from_address',
        ),
    ]
