# Generated by Django 5.0.4 on 2024-08-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_form_address_itinerary_input_from_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary_input',
            old_name='form_date',
            new_name='from_date',
        ),
    ]
