# Generated by Django 5.0.4 on 2024-08-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_form_date_itinerary_input_from_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHOICES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=154, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='itinerary_input',
            name='preferences',
        ),
        migrations.AddField(
            model_name='itinerary_input',
            name='preferences',
            field=models.ManyToManyField(to='app.choices'),
        ),
    ]
