# Generated by Django 5.0.4 on 2024-08-25 21:38

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_choices_remove_itinerary_input_preferences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary_input',
            name='preferences',
        ),
        migrations.DeleteModel(
            name='CHOICES',
        ),
        migrations.AddField(
            model_name='itinerary_input',
            name='preferences',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('adventure', 'Adventure: Activities like hiking, rafting, zip-lining, etc.'), ('cultural', 'Cultural: Museums, historical sites, cultural tours, local experiences.'), ('relaxation', 'Relaxation: Beach resorts, spas, leisurely activities.'), ('nature_wildlife', 'Nature & Wildlife: National parks, safaris, nature trails, bird watching.'), ('amusement_parks', 'Amusement Parks: Theme parks, water parks, fun fairs.'), ('religious_spiritual', 'Religious/Spiritual: Pilgrimages, visits to temples, churches, mosques, meditation retreats.'), ('trekking', 'Trekking: Mountain treks, hiking trails, nature walks.'), ('food_culinary', 'Food & Culinary: Food tours, cooking classes, street food experiences, wine tasting.'), ('shopping', 'Shopping: Markets, shopping malls, local crafts.'), ('nightlife', 'Nightlife: Bars, clubs, live music, entertainment.'), ('festivals_events', 'Festivals & Events: Local festivals, music concerts, cultural events.'), ('art_architecture', 'Art & Architecture: Art galleries, architectural landmarks, design tours.'), ('photography', 'Photography: Scenic spots, photogenic locations, guided photography tours.'), ('wellness_spa', 'Wellness & Spa: Yoga retreats, wellness centers, spa treatments.'), ('offbeat_experiences', 'Offbeat Experiences: Unique, unconventional, and less crowded places.'), ('family_friendly', 'Family-Friendly: Activities suitable for all ages, family tours.'), ('doesnt_matter', 'Does not matter: Open to any kind of experience.')], default='doesnt_matter', max_length=232),
        ),
    ]
