# Generated by Django 5.0.4 on 2024-08-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_itinerary_weather_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='weather_data',
            field=models.JSONField(null=True),
        ),
    ]
