# Generated by Django 5.0.4 on 2024-08-26 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_itinerary_weather_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='weather_data',
        ),
        migrations.AddField(
            model_name='itinerary_input',
            name='itinerary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.itinerary'),
        ),
    ]
